apiVersion: v2
name: tx-gateway
description: Helm chart for a stateless RPC gateway service, suitable for Web3/API use cases, with best practices for K8s production workloads.
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/amalkukian/devops-tx-gateway
sources:
  - https://github.com/amalkukian/devops-tx-gateway
icon: https://www.svgrepo.com/show/303448/kubernetes-logo.svg
keywords:
  - rpc
  - gateway
  - web3
  - blockchain
maintainers:
  - name: Amal Kukian
    email: amal@example.com
